<?php
/**
 * Created by PhpStorm.
 * User: dam1r89
 * Date: 9/14/14
 * Time: 3:20 PM
 */

namespace dam1r89\ProtoGenerator;


class UnderscoreCompilerMock extends UnderscoreCompiler{

    public function setContextData($contextData)
    {
        parent::setContextData($contextData); // TODO: Change the autogenerated stub
    }


    public function getContextData(){
        return $this->contextData;
    }


}
